version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/.github/actions/prepare"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directories:
      - "/"
    schedule:
      interval: "monthly"
    groups:
      pip:
        patterns:
          - "*"
