kind: pipeline
name: default

globals:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:

  - name: dry_run_build
    image: plugins/docker
    settings:
      <<: *docker_creds
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [dry-run-built]
      cache_from:
        - quay.io/natlibfi/annif:builder
        - quay.io/natlibfi/annif:latest
      dry_run: true
    when:
      event:
      - push
      - pull_request

  - name: build_and_publish_builder
    image: plugins/docker
    settings:
      <<: *docker_creds
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [builder]
      cache_from:
        - quay.io/natlibfi/annif:builder
      target: builder
    when:
      branch:
      - drone-caching
      event:
      - push

  - name: build_and_publish
    image: plugins/docker
    settings:
      <<: *docker_creds
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [latest]
      cache_from:
        - quay.io/natlibfi/annif:builder
        - quay.io/natlibfi/annif:latest
    when:
      branch:
      - drone-caching
      event:
      - push

  - name: build_publish_and_tag_with_release_version
    image: plugins/docker
    settings:
      <<: *docker_creds
      registry: quay.io
      repo: quay.io/natlibfi/annif
      auto_tag: true
    when:
      branch:
      - master
      event:
      - tag
