kind: pipeline
name: default

globals:
  - &docker_settings
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: quay.io
    repo: quay.io/natlibfi/annif

steps:

  - name: dry_run_build
    image: plugins/docker
    settings:
      <<: *docker_settings
      tags: [dry-run-built]
      cache_from:
        - quay.io/natlibfi/annif:builder
        - quay.io/natlibfi/annif:latest
      dry_run: true
    when:
      event:
      - pull_request

  - name: build_and_publish_builder
    image: plugins/docker
    settings:
      <<: *docker_settings
      tags: [builder]
      cache_from:
        - quay.io/natlibfi/annif:builder
      target: builder
    when:
      branch:
      - master
      event:
      - push

  - name: build_and_publish
    image: plugins/docker
    settings:
      <<: *docker_settings
      tags: [latest]
      cache_from:
        - quay.io/natlibfi/annif:builder
        - quay.io/natlibfi/annif:latest
    when:
      branch:
      - master
      event:
      - push

  - name: build_publish_and_tag_with_release_version
    image: plugins/docker
    settings:
      <<: *docker_settings
      auto_tag: true
    when:
      event:
      - tag

---
kind: secret
name: docker_username
data: oheObzdd1LO5wRaJ3s4KjTWv28czYEykUEff28/wnElY3+2yeBCNa4QnY+4g8iUtv+ChwleiPoDoeQ==
---
kind: secret
name: docker_password
data: AVT0+HVr3/gGKoinBv2ebQBVQ59WErQw48YEEQvY+y7vfFQPjS7M8jkoiNCcPATfT1/qg3pbGl3Da0JlBqw+UxLB2y5OeF7ABrj3lpWdIE1QcPy/E/TdKc7QCGg=
