FROM quay.io/natlibfi/annif

WORKDIR /Annif

USER root

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		curl

RUN pip install pipenv --no-cache-dir \
	&& pipenv install --system --skip-lock --dev

COPY . .

USER annif_user

CMD annif
