FROM python:3.6-slim

# TODO Using old pip version because --no-cache-dir doesn't seem to work in 19.1.1 
# TODO Disable caching in pipenv, maybe EXPORT PIP_NO_CACHE_DIR=false 
RUN pip install --upgrade pip==18.1 \
	&& pip install pipenv --no-cache-dir

# Files needed by pipenv install:
COPY Pipfile Pipfile.lock README.md setup.py /Annif/
WORKDIR /Annif

# TODO Handle occasional timeout in nltk.downloader leading failed build
RUN pipenv install --system --deploy --ignore-pipfile \
	&& python -m nltk.downloader punkt

COPY annif annif

CMD annif
