name: Prepare
description:
inputs:
  python-version:
    required: true
  poetry-version:
    required: true
outputs:
  cache-matched-key:
    value: ${{ steps.restore-cache.outputs.cache-matched-key }}
runs:
  using: "composite"
  steps:
    - name: Restore cached Poetry installation and its cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/pipx/venvs
          ~/.local/bin
          ~/.cache/pypoetry/
        key: ignore-me
        restore-keys: |
          poetry-installation-and-cache-${{ inputs.python-version }}-${{ inputs.poetry-version }}-
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
        poetry env use ${{ inputs.python-version }}
