name: Prepare
description:
inputs:
  os:
    required: true
  python-version:
    required: true
  poetry-version:
    required: true
outputs:
  cache-matched-key:
    value: ${{ steps.restore-cache.outputs.cache-matched-key }}
runs:
  using: "composite"
  steps:
    - name: Restore cached Poetry installation and its cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/pipx/venvs
          ~/.local/bin
          ~/.cache/pypoetry/
        key: ignore-me
        restore-keys: |
          poetry-installation-and-cache-${{ inputs.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}-
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: fix installation on macos using /tmp dir
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "PIPX_HOME=/tmp/.cache/pipx" >> "$GITHUB_ENV"
        echo "PIPX_BIN_DIR=/tmp/.local/bin" >> "$GITHUB_ENV"
        echo "/tmp/.local/bin" >> $GITHUB_PATH
    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry==${{ inputs.poetry-version }} --python $(which python${{ inputs.python-version }})
        pipx ensurepath
