name: Prepare
description:
inputs:
  python-version:
    required: true
  poetry-version:
    required: true
outputs:
  cache-matched-key:
    value: ${{ steps.restore-cache.outputs.cache-matched-key }}
runs:
  using: "composite"
  steps:
    - name: Restore cached Poetry installation and its cache
      id: restore-cache
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809  # v4.2.4
      with:
        path: |
          ~/.cache/pipx/venvs
          ~/.local/bin
          ~/.cache/pypoetry/
        key: ignore-me
        restore-keys: |
          python-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
        poetry env use ${{ inputs.python-version }}
