name: "Docker rebuild"
on: workflow_dispatch
permissions:
  contents: read

jobs:
  rebuild-docker-images:
    name: "Docker rebuild"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - name: "Build for testing"
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
      with:
        push: false
        tags: test-image
    - name: "Test with pytest"
      run: |
        docker run --rm --workdir /Annif test-image pytest -p no:cacheprovider
    - name: Login to Quay.io
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3.7.0
      with:
        registry: quay.io
        username: ${{ secrets.YHTEENTOIMIVUUSPALVELUT_QUAY_IO_USERNAME }}
        password: ${{ secrets.YHTEENTOIMIVUUSPALVELUT_QUAY_IO_PASSWORD }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051  # v5.10.0
      with:
        images: quay.io/natlibfi/annif
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}},suffix=-{{date 'YYYYMMDD'}}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Build and push to Quay.io
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
